const columns = [
  { name: "No", uid: "id" },
  { name: "No logement", uid: "num_de_log" },
  { name: "Occupé Par", uid: "nom", sortable: true },
  { name: "Profession/Type de Logement", uid: "type_log", sortable: true },
  { name: "Amelioré", uid: "ameliored", sortable: true},
  { name: "Pièces ( Superficie m² )", uid: "mc"},
  { name: "Quotas d'électricité (kWh / mois) ", uid: "quotaE"},
  { name: "Quotas d'eau (m³ / mois)", uid: "quotaW"},
  { name: "Equipements", uid: "equip" },
  { name: "Actions", uid: "actions" },
];

const users = [
  {
    id: 1,
    num_de_log: "LOG001",
    nom: "John Doe",
    type_log: "Cadre",
    ameliored: "Oui",
    mc: "5 pièces (120m²)",
    quotaE:"500",
    quotaW:"20",
  },
  {
    id: 2,
    num_de_log: "LOG002",
    nom: "Jane Smith",
    type_log: "Cadre",
    ameliored: "Non",
    mc: "4 pieces (90m²)",
    quotaE:"350",
    quotaW:"15",
  },
  {
    id: 3,
    num_de_log: "LOG003",
    nom: "Alice Johnson",
    type_log: "Ouvrier ",
    ameliored: "Oui",
    mc: "3 pièces (70m²)",
    quotaE:"350",
    quotaW:"16",
  },
  {
    id: 4,
    num_de_log: "LOG004",
    nom: "Michael Brown",
    type_log: "Agent de maitrise",
    ameliored: "Oui",
    mc: "4 pièces (85m²)",
    quotaE:"400",
    quotaW:"18",
  },
  {
    id: 5,
    num_de_log: "LOG005",
    nom: "Emily Wilson",
    type_log: "Agent de maitrise  ",
    ameliored: "Non",
    mc: "3 pièces (65m²)",
    quotaE:"300",
    quotaW:"14",
  },
  {
    id: 6,
    num_de_log: "LOG006",
    nom: "--",
    type_log: "Cadre ",
    ameliored: "Oui",
    mc: "5 pièces (120m²)",
    quotaE:"500",
    quotaW:"20",
  },
  {
    id: 7,
    num_de_log: "LOG007",
    nom: "--",
    type_log: "Ouvrier  ",
    ameliored: "Non",
    mc: "2 pièces (50m²)",
    quotaE:"250",
    quotaW:"12",
  },
  {
    id: 8,
    num_de_log: "LOG008",
    nom: "Daniel Martinez",
    type_log: "Ouvrier ",
    ameliored: "Non",
    mc: "2 pièces (50m²)",
    quotaE:"250",
    quotaW:"12",
  },
  {
    id: 9,
    num_de_log: "LOG009",
    nom: "Sophia Taylor",
    type_log: "Cadre ",
    ameliored: "Oui",
    mc:  "5 pièces (120m²)",
    quotaE:"500",
    quotaW:"20",
  },
  {
    id: 10,
    num_de_log: "LOG0010",
    nom: "William Miller",
    type_log: "Ouvrier ",
    ameliored: "Non",
    mc: "2 pièces (50m²)",
    quotaE:"250",
    quotaW:"12",
  },
];

export { columns, users };
